# Generated by Django 4.1.3 on 2022-12-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_is_student_user_is_learner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_shareable',
            field=models.BooleanField(default=False),
        ),
    ]
