# Generated by Django 4.1.3 on 2022-12-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_user_friends_friend_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
