# Generated by Django 4.1.3 on 2022-12-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_friendrequest_delete_friend_request_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_friend_request_1',
        ),
        migrations.RemoveConstraint(
            model_name='friendrequest',
            name='unique_friend_request_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddConstraint(
            model_name='friendrequest',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_friend_request'),
        ),
    ]
