# Generated by Django 4.1.3 on 2022-12-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_friendrequest_unique_friend_request_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FriendRequest',
            new_name='Friends',
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.CheckConstraint(check=models.Q(('from_user', models.F('to_user')), _negated=True), name='no_self_friendships'),
        ),
    ]
