# Generated by Django 4.1.3 on 2023-03-07 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_rename_friendrequest_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='km_driven',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='minutes_driven',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=50)),
                ('severity', models.FloatField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
