# Generated by Django 4.1.7 on 2023-05-09 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelsession',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='levelsession',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='backend.level'),
        ),
        migrations.AlterField(
            model_name='levelsession',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='levelsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='violation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to=settings.AUTH_USER_MODEL),
        ),
    ]
